# Allgemeine Infrastruktur-Server
common:
  hosts:
    netbox.as209894.ffi.ms:
      ansible_ssh_host: 128.140.61.120
      server_aufgabe: "NetBox-Server"
    secret.ffi.ms:
      ansible_ssh_host: secret.ffi.ms
      server_aufgabe: "Passbolt-Server"
    xwiki.ffi.ms:
      ansible_ssh_host: wiki-neu.ffi.ms
      server_aufgabe: "Wiki-Server"

uffdsso:
  hosts:
    sso.ffi.ms:
      ansible_ssh_host: sso.ffi.ms
      server_aufgabe: "Uffd-SSO-Server"
