# Allgemeine Infrastruktur-Server
common:
  hosts:
    secret.ffi.ms:
      ansible_host: secret.ffi.ms
      server_aufgabe: "Passbolt-Server"
    wiki.ffi.ms:
      ansible_host: wiki-neu.ffi.ms
      server_aufgabe: "Wiki-Server"
    sso.ffi.ms:
      ansible_host: sso.ffi.ms
      server_aufgabe: "Uffd-SSO-Server"
    atlas-ber.as209894.ffi.ms:
      ansible_host: atlas-ber.as209894.ffi.ms
      server_aufgabe: "RIPE Atlas Probe Berlin"
    atlas-fra.as209894.ffi.ms:
      ansible_host: atlas-fra.as209894.ffi.ms
      server_aufgabe: "RIPE Atlas Probe Frankfurt"
    lg.as209894.ffi.ms:
      ansible_host: lg.as209894.ffi.ms
      server_aufgabe: "AS209894 Fernglas"

asrouter:
  children:
    fra:
      hosts:
        fra-a.as209894.ffi.ms:
          ansible_host: 45.152.127.50
          server_aufgabe: "AS-Router und Hypervisor"
        fra-b.as209894.ffi.ms:
          ansible_host: 194.50.19.2
          server_aufgabe: "AS-Router und Hypervisor"
    ber:
      hosts:
        ber-a.as209894.ffi.ms:
          ansible_host: 217.197.83.217
          server_aufgabe: "AS-Router und Hypervisor"
        ber-b.as209894.ffi.ms:
          ansible_host: 217.197.83.222
          server_aufgabe: "AS-Router und Hypervisor"

proxmox:
  hosts:
    msr-a.srv.ffi.ms:
      ansible_host: msr-a.srv.ffi.ms
      server_aufgabe: "Proxmox-Hypervisor"
    remue.srv.ffi.ms:
      ansible_host: remue.srv.ffi.ms
      server_aufgabe: "Proxmox-Hypervisor"
    asterix.srv.ffi.ms:
      ansible_host: asterix.srv.ffi.ms
      server_aufgabe: "Proxmox-Hypervisor"
    obelix.srv.ffi.ms:
      ansible_host: obelix.srv.ffi.ms
      server_aufgabe: "Proxmox-Hypervisor"
    destructivus.srv.ffi.ms:
      ansible_host: destructivus.srv.ffi.ms
      server_aufgabe: "Proxmox-Hypervisor"

media_mirror:
  hosts:
    media-mirror.ffi.ms:
      ansible_host: media-mirror.ffi.ms
      server_aufgabe: "media.freifunk.net mirror"

ns:
  children:
    ns_primary:
      hosts:
        ns00.as209894.de:
          ipv4: 217.70.1.164
          ipv6: 2a14:440:2100::4
          ansible_host: "{{ ipv4 }}"
          server_aufgabe: "Hidden Primary Nameserver (FFI)"
    ns_secondary:
      hosts:
        ns01.as209894.de:
          ipv4: 159.69.223.64
          ipv6: 2a01:4f8:1c1c:8987::1
          ansible_host: "{{ ipv4 }}"
          server_aufgabe: "Autoritative Secondary Nameserver (????)"
        ns02.as209894.de:
          ipv4: 217.70.1.147
          ipv6: 2a14:440:1200::3
          ansible_host: "{{ ipv4 }}"
          server_aufgabe: "Autoritative Secondary Nameserver (FFI)"
        ns03.as209894.de:
          ipv4: 148.251.208.172
          ipv6: 2a01:4f8:191:21e1::172
          ansible_host: "{{ ipv4 }}"
          server_aufgabe: "Autoritative Secondary Nameserver (Hetzner)"
        ns04.as209894.de:
          ipv4: 212.3.68.150
          ipv6: 2a02:1799:9::150
          ansible_host: "{{ ipv4 }}"
          server_aufgabe: "Autoritative Secondary Nameserver (Webdiscount)"
