# Allgemeine Infrastruktur-Server
common:
  hosts:
    monitor.ffi.ms:
      ansible_ssh_host: 159.69.223.64
      server_aufgabe: "Monitoring-Server"
    netbox.as209894.ffi.ms:
      ansible_ssh_host: 128.140.61.120
      server_aufgabe: "NetBox-Server"
    secret.ffi.ms:
      ansible_ssh_host: secret.ffi.ms
      server_aufgabe: "Passbolt-Server"
    wiki.ffi.ms:
      ansible_ssh_host: wiki-neu.ffi.ms
      server_aufgabe: "Wiki-Server"
    sso.ffi.ms:
      ansible_ssh_host: sso.ffi.ms
      server_aufgabe: "Uffd-SSO-Server"

asrouter:
  hosts:
    fra-a.as209894.ffi.ms:
      ansible_ssh_host: 45.152.127.50
      server_aufgabe: "AS-Router und Hypervisor"
    fra-b.as209894.ffi.ms:
      ansible_ssh_host: 194.50.19.2
      server_aufgabe: "AS-Router und Hypervisor"
    ber-a.as209894.ffi.ms:
      ansible_ssh_host: 217.197.83.217
      server_aufgabe: "AS-Router und Hypervisor"
    ber-b.as209894.ffi.ms:
      ansible_ssh_host: 217.197.83.222
      server_aufgabe: "AS-Router und Hypervisor"

proxmox:
  hosts:
    msr-a.srv.ffi.ms:
      ansible_ssh_host: msr-a.srv.ffi.ms
      server_aufgabe: "Proxmox-Hypervisor"
    remue.srv.ffi.ms:
      ansible_ssh_host: remue.srv.ffi.ms
      server_aufgabe: "Proxmox-Hypervisor"

media-mirror:
  hosts:
    media-mirror.ffi.ms:
      ansible_ssh_host: media-mirror.ffi.ms
      server_aufgabe: "media.freifunk.net mirror"

dienste_dns_hidden:
  hosts:
    hns-ffi.srv.ffi.ms:
      ipv4: 45.154.111.164
      ipv6: 2a14:440:2100::4
      ansible_ssh_host: "{{ ipv4 }}"
      server_aufgabe: "Hidden Nameserver fuer FFI"
