---
- name: Install Caddy
  apt:
    name:
      - caddy
    state: present
    update_cache: yes

- name: create Caddyfile
  template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    owner: root
    group: root
    mode: '0644'
  notify: Restart caddy
