---

- name: Install unattended-upgrades package
  apt:
    pkg: "unattended-upgrades"
    state: present
    update_cache: yes
    cache_valid_time: 1800

- name: Enable unattended upgrades
  template:
    src: 10periodic.j2
    dest: /etc/apt/apt.conf.d/10periodic

- name: Configure unattended upgrades on Debian
  template:
    src: 52unattended-upgrades-local-debian.j2
    dest: /etc/apt/apt.conf.d/52unattended-upgrades-local
  when: ansible_distribution == 'Debian'

- name: Configure unattended upgrades on Ubuntu
  template:
    src: 52unattended-upgrades-local-debian.j2
    dest: /etc/apt/apt.conf.d/52unattended-upgrades-local-debian.j2
  when: ansible_distribution == 'Ubuntu'
