---
- name: Restart uwsgi
  systemd:
    name: uwsgi
    state: restarted
    enabled: true

- name: Restart caddy
  systemd:
    name: caddy
    state: restarted
    enabled: true

- name: Restart nginx
  systemd:
    name: nginx
    state: restarted
    enabled: true
